<?php

namespace OCA\Libresign\3rdparty;

// autoload_real.php @generated by Composer
/** @internal */
class ComposerAutoloaderInitLibresign
{
    private static $loader;
    public static function loadClassLoader($class)
    {
        if ('Composer\\Autoload\\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }
    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }
        require __DIR__ . '/platform_check.php';
        \spl_autoload_register(array('OCA\\Libresign\\3rdparty\\ComposerAutoloaderInitLibresign', 'loadClassLoader'), \true, \true);
        self::$loader = $loader = new \OCA\Libresign\3rdparty\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        \spl_autoload_unregister(array('ComposerAutoloaderInitLibresign', 'loadClassLoader'));
        require __DIR__ . '/autoload_static.php';
        \call_user_func(\OCA\Libresign\3rdparty\Composer\Autoload\ComposerStaticInitLibresign::getInitializer($loader));
        $loader->setClassMapAuthoritative(\true);
        $loader->register(\true);
        $filesToLoad = \OCA\Libresign\3rdparty\Composer\Autoload\ComposerStaticInitLibresign::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = \true;
                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }
        return $loader;
    }
}
// autoload_real.php @generated by Composer
/** @internal */
\class_alias('OCA\\Libresign\\3rdparty\\ComposerAutoloaderInitLibresign', 'ComposerAutoloaderInitLibresign', \false);
