<?php

namespace OCA\Libresign\3rdparty;

// autoload_namespaces.php @generated by Composer
$vendorDir = \dirname(__DIR__);
$baseDir = \dirname($vendorDir);
return array('Smalot\\PdfParser\\' => array($vendorDir . '/smalot/pdfparser/src'));
